source 'http://rubygems.org'

gem 'rails',                '~> 4.2.0'
gem 'unicorn'
gem 'pg'
gem 'devise'
gem 'default_value_for'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'will_paginate'
gem 'simple_form'
gem 'cancancan'
gem 'csv_builder'
gem 'validates_timeliness'
gem 'paper_trail',          '~> 3.0.6'
gem 'figaro'
gem 'will_paginate-bootstrap'
gem 'newrelic_rpm'
gem 'therubyracer'
gem 'less-rails'
gem 'twitter-bootstrap-rails'
gem 'less'
gem 'less-rails-bootstrap'
gem 'sass-rails'
gem 'coffee-rails'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
end
